title: Luke Hall
theme: minimal-mistakes-jekyll

# Site navigation links (GitHub, LinkedIn, Email)
navigation:
  - title: "Home"
    url: /
  - title: "About"
    url: /about/
  - title: "GitHub"
    url: "https://github.com/HallL415/Optimisation"
  - title: "LinkedIn"
    url: "https://www.linkedin.com/in/your-linkedin-profile"
  - title: "Email"
    url: "mailto:your-email@example.com"
