title: Luke Hall
theme: just-the-docs

# Navigation links
nav_order: 
  - Home
  - About

# External links (GitHub, LinkedIn, Email)
external_links:
  - name: "GitHub"
    url: "https://github.com/HallL415/Optimisation"
  - name: "LinkedIn"
    url: "https://www.linkedin.com/in/your-linkedin-profile"
  - name: "Email"
    url: "mailto:your-email@example.com"
